container:
  image: gcr.io/cloud-builders/bazel@sha256:240b796c49e8c8a11c7fe49e83fd0d4fdaa32998accccd4465dfe2df3be13230
task:
  build_script: bazel build //... --jobs=1 --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
