container:
  image: gcr.io/cloud-builders/bazel@sha256:b5549c3d5b3975b59dc22ec4fc59cad144879f1ab7803f7c1d17217efdbeb55e
task:
  build_script: bazel build //... --jobs=1 --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
