# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
    - image: gcr.io/cloud-builders/bazel@sha256:79b4915be0d73981b04b6dbdf06e531b1ea1121a9bcb9b6561439054f6bd9c87
    steps:
    - run:
        command: bazel build //... --jobs=1
        name: Bazel Build
workflows:
  welcome:
    jobs:
    - build
