# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
    - image: gcr.io/cloud-builders/bazel@sha256:b5549c3d5b3975b59dc22ec4fc59cad144879f1ab7803f7c1d17217efdbeb55e
    steps:
    - checkout
    - run:
        command: bazel build //... --jobs=1
        name: Bazel Build
workflows:
  build:
    jobs:
    - build
