# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
    - image: gcr.io/cloud-builders/bazel@sha256:240b796c49e8c8a11c7fe49e83fd0d4fdaa32998accccd4465dfe2df3be13230
    steps:
    - checkout
    - run:
        command: bazel build //... --jobs=1
        name: Bazel Build
workflows:
  build:
    jobs:
    - build
