# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
    - image: gcr.io/cloud-builders/bazel@sha256:3c561895ff1268563114c7b1ef61cdfdd43a0b6812edb4e5b9e3a74f62173932
    steps:
    - checkout
    - run:
        command: bazel build //... --jobs=1
        name: Bazel Build
workflows:
  build:
    jobs:
    - build
