apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: registry.hub.docker.com/rickyp999/helloworld:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
